### ISSUE TITLE
dog/bicycle/car example error

### ISSUE THREAD

**Issue by tooptoop4** [awslabs/djl#472] opened 2020-12-28 23:21 UTC
## Question

I am getting this error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at ai.djl.modality.cv.translator.SingleShotDetectionTranslator.processOutput(SingleShotDetectionTranslator.java:63)
	at ai.djl.modality.cv.translator.SingleShotDetectionTranslator.processOutput(SingleShotDetectionTranslator.java:29)
	at ai.djl.inference.Predictor.processOutputs(Predictor.java:220)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:176)
	at ai.djl.inference.Predictor.predict(Predictor.java:128)
	at SimpleObjectDetector.detectObject(SimpleObjectDetector.java:32) ---> predictor.predict(BufferedImageFactory.getInstance().fromImage(image));
```

code:
```

public class SimpleObjectDetector implements ObjectDetector<BufferedImage> {

    private final ZooModel<Image, DetectedObjects> model;

    public SimpleObjectDetector(ZooModel<Image, DetectedObjects> model) {
        this.model = model;
    }

    @Override
    public Map<String, List<BoundingBox>> detectObject(BufferedImage image)
            throws ClassificationException {
        try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
            DetectedObjects detectedObjects =
                    predictor.predict(BufferedImageFactory.getInstance().fromImage(image));
            Map<String, List<BoundingBox>> ret = new ConcurrentHashMap<>();

            int imageWidth = image.getWidth();
            int imageHeight = image.getHeight();

            List<DetectedObjects.DetectedObject> detections = detectedObjects.items();
            for (DetectedObjects.DetectedObject detection : detections) {
                String className = detection.getClassName();
                float probability = (float) detection.getProbability();
                Rectangle rect = detection.getBoundingBox().getBounds();

                int x = (int) (rect.getX() * imageWidth);
                int y = (int) (rect.getY() * imageHeight);
                float w = (float) (rect.getWidth() * imageWidth);
                float h = (float) (rect.getHeight() * imageHeight);

                ret.compute(
                        className,
                        (k, list) -> {
                            if (list == null) {
                                list = new ArrayList<>();
                            }
                            list.add(new BoundingBox(className, probability, x, y, w, h));
                            return list;
                        });
            }

            return ret;
        } catch (TranslateException e) {
            throw new ClassificationException("Failed to process output", e);
        }
    }
}

public class ImageDetectPlugin implements FilePlugin {

    @Override
    public Iterator getIterator(ByteSource byteSource)
    {
      ArrayList al = new ArrayList();
        try (ThreadContextClassLoader ignored = new ThreadContextClassLoader(getClass().getClassLoader())) {
            Criteria<Image, DetectedObjects> criteria =
                    Criteria.builder()
                            .setTypes(Image.class, DetectedObjects.class)
                            .optApplication(Application.CV.OBJECT_DETECTION)
                            .optArgument("threshold", 0.3)
                            .build();
            //.optArtifactId("yolo")
            System.out.println("criteria:");
            System.out.println(criteria);
            try {
                ModelZoo.listModels();
                System.out.println("inb:");
                ModelZoo.listModels(criteria);
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ModelNotFoundException e) {
                e.printStackTrace();
            }
            try (ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria)) {
                    System.out.println("model:");
                    System.out.println(model);
                SimpleObjectDetector objectDetector = new SimpleObjectDetector(model);
                    System.out.println("objectDetector:");
                    System.out.println(objectDetector);
                URL imageUrl = null;
                imageUrl = new URL("https://djl-ai.s3.amazonaws.com/resources/images/dog_bike_car.jpg");

                BufferedImage inputImage = null;
                inputImage = ImageIO.read(imageUrl);
                Map<String, List<BoundingBox>> result = objectDetector.detectObject(inputImage);

                for (List<BoundingBox> boundingBoxes : result.values()) {
                    for (BoundingBox boundingBox : boundingBoxes) {
                        System.out.println(boundingBox.toString());
                        al.add(Arrays.asList(boundingBox.toString()));
                    }
                }
            } catch (IOException | ModelNotFoundException | MalformedModelException e) {
                throw new RuntimeException(e.getMessage());
            }
        }
        return al.iterator();
    }
}
```

logs printed before the stack trace:
```
	stdout	criteria:
	stdout	Criteria:
	Application: CV.OBJECT_DETECTION
	Input: interface ai.djl.modality.cv.Image
	Output: class ai.djl.modality.cv.output.DetectedObjects
	Arguments: {"threshold":0.3}
	No translator supplied

	stdout	inb:
	ai.djl.repository.zoo.ModelZoo	Loading model with Criteria:
	Application: CV.OBJECT_DETECTION
	Input: interface ai.djl.modality.cv.Image
	Output: class ai.djl.modality.cv.output.DetectedObjects
	Arguments: {"threshold":0.3}
	No translator supplied

	ai.djl.repository.zoo.ModelZoo	Searching model in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
	ai.djl.repository.zoo.ModelZoo	No model zoo found in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
	ai.djl.repository.zoo.ModelZoo	Searching model in zoo provider: ai.djl.basicmodelzoo.BasicZooProvider
	ai.djl.repository.zoo.ModelZoo	Checking ModelLoader: ai.djl.zoo:resnet CV.IMAGE_CLASSIFICATION [
	ai.djl.zoo:resnet:0.0.2 {"layers":"50","flavor":"v1","dataset":"cifar10"}
]
	ai.djl.repository.zoo.ModelZoo	application mismatch for ModelLoader: ai.djl.zoo:resnet
	ai.djl.repository.zoo.ModelZoo	Checking ModelLoader: ai.djl.zoo:mlp CV.IMAGE_CLASSIFICATION [
	ai.djl.zoo:mlp:0.0.3 {"dataset":"mnist"}
]
	ai.djl.repository.zoo.ModelZoo	application mismatch for ModelLoader: ai.djl.zoo:mlp
	ai.djl.repository.zoo.ModelZoo	Checking ModelLoader: ai.djl.zoo:ssd CV.OBJECT_DETECTION [
	ai.djl.zoo:ssd:0.0.2 {"flavor":"tiny","dataset":"pikachu"}
]
	ai.djl.repository.Resource	Preparing artifact: zoo, ai.djl.zoo:ssd:0.0.2 {"flavor":"tiny","dataset":"pikachu"}
	ai.djl.repository.AbstractRepository	Files have been downloaded already: /Users/me/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/zoo/ssd/tiny/pikachu/0.0.2
	ai.djl.util.cuda.CudaUtils	cudart library not found.
	ai.djl.mxnet.jna.LibUtils	Using cache dir: /Users/me/.djl.ai/mxnet
	ai.djl.mxnet.jna.LibUtils	Downloading libmxnet.dylib ...
	ai.djl.mxnet.jna.LibUtils	Loading mxnet library from: /Users/me/.djl.ai/mxnet/1.7.0-backport-mkl-osx-x86_64/libmxnet.dylib
	ai.djl.engine.Engine	Engine loaded from provider: MXNet
	ai.djl.engine.Engine	Found default engine: MXNet
	ai.djl.BaseModel	Try to load model from /Users/me/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/zoo/ssd/tiny/pikachu/0.0.2/ssd-0000.params
	ai.djl.BaseModel	Loading saved model: pikachu-ssd parameter
	ai.djl.BaseModel	DJL model loaded successfully
	stdout	model:
	stdout	ai.djl.repository.zoo.ZooModel@7e4d43ea
	stdout	objectDetector:

```

**Comment by frankfliu** [comment] 2020-12-29 00:25
@tooptoop4 based on the log, the object detection model get loaded is pikachu-ssd. It can only detect pikach in the image.

All the models in `ai.djl:model-zoo` package is only used for demo purpose. For general purpose object detection, you'd better use models from mxnet model zoo (`ai.djl-mxnet:mxnet-model-zoo`) or pytorch model zoo.

And you can specify with model you'd like to use: 

```
Criteria<Image, DetectedObjects> criteria =
                    Criteria.builder()
                            .setTypes(Image.class, DetectedObjects.class)
                            .optApplication(Application.CV.OBJECT_DETECTION)
                            .optArtifactsId("yolo")
                            .optArgument("threshold", 0.3)
                            .build();
```

The code seems fine to me, I will try your code and see why you get exception on pikach-ssd.

**Comment by frankfliu** [comment] 2020-12-29 03:34
@tooptoop4 I'm able to reproduce your issue. This is a bug in Pikachu model loader. During refactoring the SingleShotDetectionTraslator, Pikachu ssd's translator output processing code is lost. I will create a PR to fix this issue.

But for the mean time, you can use yolo or other ssd model (.e.g resnet50, mobilenet_v2, vgg16 etc)

**Comment by tooptoop4** [comment] 2020-12-29 08:12
@frankfliu 

Thanks, after that change I now get some results but it is showing cat instead of dog, how to fix?
```
BoundingBox{id=0, x=112.0, y=128.0, width=456.74023, height=331.11517, label=bicycle, score=0.97306085}
BoundingBox{id=0, x=476.0, y=79.0, width=204.21478, height=93.42342, label=car, score=0.9836603}
BoundingBox{id=0, x=133.0, y=235.0, width=184.42851, height=293.16937, label=cat, score=0.8731121}
```

logs are:
```
	stdout	Criteria:
	Application: CV.OBJECT_DETECTION
	Input: interface ai.djl.modality.cv.Image
	Output: class ai.djl.modality.cv.output.DetectedObjects
	ArtifactId: yolo
	Arguments: {"threshold":0.3}
	No translator supplied

	stdout	inb:
	ai.djl.repository.zoo.ModelZoo	Loading model with Criteria:
	Application: CV.OBJECT_DETECTION
	Input: interface ai.djl.modality.cv.Image
	Output: class ai.djl.modality.cv.output.DetectedObjects
	ArtifactId: yolo
	Arguments: {"threshold":0.3}
	No translator supplied

	ai.djl.repository.zoo.ModelZoo	Searching model in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
	ai.djl.repository.zoo.ModelZoo	No model zoo found in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
	ai.djl.repository.zoo.ModelZoo	Searching model in zoo provider: ai.djl.mxnet.zoo.MxZooProvider
	ai.djl.repository.zoo.ModelZoo	Checking ModelLoader: ai.djl.mxnet:ssd CV.OBJECT_DETECTION [
	ai.djl.mxnet:ssd:0.0.1 {"size":"512","backbone":"resnet50","flavor":"v1","dataset":"voc"}
	ai.djl.mxnet:ssd:0.0.1 {"size":"512","backbone":"vgg16","flavor":"atrous","dataset":"coco"}
	ai.djl.mxnet:ssd:0.0.1 {"size":"512","backbone":"mobilenet1.0","dataset":"voc"}
	ai.djl.mxnet:ssd:0.0.1 {"size":"300","backbone":"vgg16","flavor":"atrous","dataset":"voc"}
]
	ai.djl.repository.zoo.ModelZoo	artifactId mismatch for ModelLoader: ai.djl.mxnet:ssd
	ai.djl.repository.zoo.ModelZoo	Checking ModelLoader: ai.djl.mxnet:yolo CV.OBJECT_DETECTION [
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"voc","version":"3","backbone":"darknet53","imageSize":"320"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"voc","version":"3","backbone":"darknet53","imageSize":"416"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"voc","version":"3","backbone":"mobilenet1.0","imageSize":"320"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"voc","version":"3","backbone":"mobilenet1.0","imageSize":"416"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"darknet53","imageSize":"320"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"darknet53","imageSize":"416"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"darknet53","imageSize":"608"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"mobilenet1.0","imageSize":"320"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"mobilenet1.0","imageSize":"416"}
	ai.djl.mxnet:yolo:0.0.1 {"dataset":"coco","version":"3","backbone":"mobilenet1.0","imageSize":"608"}
]
	ai.djl.repository.Resource	Preparing artifact: MXNet, ai.djl.mxnet:yolo:0.0.1 {"dataset":"voc","version":"3","backbone":"darknet53","imageSize":"320"}
	ai.djl.repository.AbstractRepository	Items to download: 3
	ai.djl.repository.AbstractRepository	Downloading artifact: https://mlrepo.djl.ai/model/cv/object_detection/ai/djl/mxnet/classes_voc.txt ...
	ai.djl.repository.AbstractRepository	Downloading artifact: https://mlrepo.djl.ai/model/cv/object_detection/ai/djl/mxnet/yolo/0.0.1/yolo3_darknet53_voc-320x320/yolo-symbol.json ...
	ai.djl.repository.AbstractRepository	Downloading artifact: https://mlrepo.djl.ai/model/cv/object_detection/ai/djl/mxnet/yolo/0.0.1/yolo3_darknet53_voc-320x320/yolo-0000.params.gz ...
	ai.djl.util.cuda.CudaUtils	cudart library not found.
	ai.djl.mxnet.jna.LibUtils	Using cache dir: /Users/me/.djl.ai/mxnet
	ai.djl.mxnet.jna.LibUtils	Loading mxnet library from: /Users/me/.djl.ai/mxnet/1.7.0-backport-mkl-osx-x86_64/libmxnet.dylib
	ai.djl.engine.Engine	Engine loaded from provider: MXNet
	ai.djl.engine.Engine	Found default engine: MXNet
	ai.djl.BaseModel	Try to load model from /Users/me/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/mxnet/yolo/voc/3/darknet53/320/0.0.1/yolo-0000.params
	ai.djl.mxnet.engine.MxModel	DJL formatted model not found, try to find MXNet model
	ai.djl.mxnet.engine.MxModel	MXNet Model /Users/me/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/mxnet/yolo/voc/3/darknet53/320/0.0.1/yolo-0000.params (float32) loaded successfully.
	stdout	model:
	stdout	ai.djl.repository.zoo.ZooModel@672e6e61
	stdout	objectDetector:
	stdout	BoundingBox{id=0, x=112.0, y=128.0, width=456.74023, height=331.11517, label=bicycle, score=0.97306085}
	stdout	BoundingBox{id=0, x=476.0, y=79.0, width=204.21478, height=93.42342, label=car, score=0.9836603}
	stdout	BoundingBox{id=0, x=133.0, y=235.0, width=184.42851, height=293.16937, label=cat, score=0.8731121}

```

also instead of 3 artefacts being downloaded at runtime, how can I get them downloaded/referenced before runtime?

**Comment by frankfliu** [comment] 2020-12-29 21:38
@tooptoop4 
I think this is model issue. For this particular case, yolo model seems not able to distinguish between cat and dog. 
if you set threshold to 0.2, you can see yolo model detected the dog:

```
 [
	class: "car", probability: 0.98366, bounds: [x=0.620, y=0.138, width=0.266, height=0.162]
	class: "bicycle", probability: 0.97306, bounds: [x=0.146, y=0.223, width=0.595, height=0.575]
	class: "cat", probability: 0.87311, bounds: [x=0.173, y=0.409, width=0.240, height=0.509]
	class: "dog", probability: 0.27398, bounds: [x=0.173, y=0.409, width=0.240, height=0.509]
]
```

Looks like "resnet50" did a better job on this image:
```
.optFilter("backbone", backbone)
```

**Comment by frankfliu** [comment] 2020-12-29 21:48
@tooptoop4
The DJL model zoo model artifacts are stored in S3 and downloaded at runtime. It will be cached in your local file system:
`~/.djl.ai/cache/repo/model/` folder.

You can download them from our S3, or copy them from the cache folder and bundle the files with your distribution package.
DJL support load model from jar file, in your code you can do:

```
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("jar:///mymodel/ssd") // load model from your own jar file
                        .build();
```

Most of DJL pre-trained object detection model are trained on [imagenet](http://www.image-net.org/). I think you may need to train your own model to better detect your own object.

**Comment by lanking520** [comment] 2021-01-29 01:36
@tooptoop4 close this issue for now. If you have futher question about SSD model, please feel free to reopen. 👍

**Closed by lanking520** 2021-01-29 01:36 UTC
Labels: question
