### ISSUE TITLE
Mx Net Engine truncates float values to integers on systems with a German locale

### ISSUE THREAD

**Issue by chenkelmann** [awslabs/djl#49] opened 2020-04-09 00:29 UTC
## Description
Operations on `MxNDArray` that take a single `Number` argument truncate the arguments decimal places which leads to erroneous calculation results. This seems to be due to a German Locale setting of the host.

E.g.: 
`System.out.println(NDManager.newBaseManager().create(1.3).add(0.7));`
prints: 
    ND: () gpu(0) float64
    1.3

This seems to affect all math operations with a single `Number` argument like `add`, `gt`, `gte`, `lt` etc.

### Expected Behavior
`float` and `double` values are passed correctly, mathematical operations yield correct results. The above line should print: 
    ND: () gpu(0) float64
    2.0

### Error Message
N/A

## How to Reproduce?
An example of the error with the console output on a German system can be found here: 
https://gist.github.com/chenkelmann/2bfa9627d79a9aaab34a46227d81aea5

### Steps to reproduce
Run the main method in the above example on a Linux system with `LC_NUMERIC=de_DE.UTF-8
`

## What have you tried to solve it?
The problem can be circumvented by creating an NDArray with the argument instead of using the methods that take `Number`: 
`System.out.println(manager.create(1.3).add(manager.create(new double[]{0.7})));`

Setting LC_NUMERIC="en_US.UTF-8" for the current process also fixes the issue (but is very fragile, as the correct working of the code depends on the current environment variables...)

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
[INFO ] - ----------System Properties----------
[INFO ] - sun.cpu.isalist: 
[INFO ] - sun.desktop: gnome
[INFO ] - sun.io.unicode.encoding: UnicodeLittle
[INFO ] - sun.cpu.endian: little
[INFO ] - java.vendor.url.bug: http://bugreport.sun.com/bugreport/
[INFO ] - file.separator: /
[INFO ] - java.vendor: Private Build
[INFO ] - sun.boot.class.path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
[INFO ] - java.ext.dirs: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
[INFO ] - java.version: 1.8.0_242
[INFO ] - java.vm.info: mixed mode
[INFO ] - awt.toolkit: sun.awt.X11.XToolkit
[INFO ] - org.apache.logging.log4j.assignedSequences: 8786
[INFO ] - user.language: en
[INFO ] - java.specification.vendor: Oracle Corporation
[INFO ] - sun.java.command: ai.djl.integration.util.DebugEnvironment
[INFO ] - java.home: /usr/lib/jvm/java-8-openjdk-amd64/jre
[INFO ] - sun.arch.data.model: 64
[INFO ] - java.vm.specification.version: 1.8
[INFO ] - java.class.path: /home/christoph/IdeaProjects/djl/integration/build/classes/java/main:/home/christoph/IdeaProjects/djl/integration/build/resources/main:/home/christoph/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.4/c51c00206bb913cd8612b24abd9fa98ae89719b1/commons-cli-1.4.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.12.1/14973e22497adaf0196d481fb99c5dc2a0b58d41/log4j-slf4j-impl-2.12.1.jar:/home/christoph/IdeaProjects/djl/basicdataset/build/libs/basicdataset-0.5.0-SNAPSHOT.jar:/home/christoph/IdeaProjects/djl/model-zoo/build/libs/model-zoo-0.5.0-SNAPSHOT.jar:/home/christoph/IdeaProjects/djl/testing/build/libs/testing-0.5.0-SNAPSHOT.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.testng/testng/6.8.1/8aebea980eee079365df20f0cf7fcac900d50250/testng-6.8.1.jar:/home/christoph/IdeaProjects/djl/mxnet/mxnet-model-zoo/build/libs/mxnet-model-zoo-0.5.0-SNAPSHOT.jar:/home/christoph/IdeaProjects/djl/mxnet/mxnet-engine/build/libs/mxnet-engine-0.5.0-SNAPSHOT.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/ai.djl.mxnet/mxnet-native-auto/1.7.0-a-SNAPSHOT/a65beb2ad0ce1f49012bda3e5898979320278027/mxnet-native-auto-1.7.0-a-SNAPSHOT.jar:/home/christoph/IdeaProjects/djl/api/build/libs/api-0.5.0-SNAPSHOT.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.26/77100a62c2e6f04b53977b9f541044d7d722693d/slf4j-api-1.7.26.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.12.1/4382e93136c06bfb34ddfa0bb8a9fb4ea2f3df59/log4j-core-2.12.1.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.12.1/a55e6d987f50a515c9260b0451b4fa217dc539cb/log4j-api-2.12.1.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.beanshell/bsh/2.0b4/a05f0a0feefa8d8467ac80e16e7de071489f0d9c/bsh-2.0b4.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.27/58c9cbf0f1fa296f93c712f2cf46de50471920f9/jcommander-1.27.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.6/a1e23e31c424d566ee27382e373d73a28fdabd88/snakeyaml-1.6.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar:/home/christoph/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.3.0/4654d1da02e4173ba7b64f7166378847db55448a/jna-5.3.0.jar
[INFO ] - user.name: christoph
[INFO ] - file.encoding: UTF-8
[INFO ] - java.specification.version: 1.8
[INFO ] - java.awt.printerjob: sun.print.PSPrinterJob
[INFO ] - user.timezone: Europe/Berlin
[INFO ] - user.home: /home/christoph
[INFO ] - os.version: 5.3.0-46-generic
[INFO ] - sun.management.compiler: HotSpot 64-Bit Tiered Compilers
[INFO ] - java.specification.name: Java Platform API Specification
[INFO ] - java.class.version: 52.0
[INFO ] - java.library.path: /usr/local/cuda/lib64::/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
[INFO ] - sun.jnu.encoding: UTF-8
[INFO ] - os.name: Linux
[INFO ] - user.variant: 
[INFO ] - java.vm.specification.vendor: Oracle Corporation
[INFO ] - java.io.tmpdir: /tmp
[INFO ] - line.separator: 

[INFO ] - java.endorsed.dirs: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
[INFO ] - os.arch: amd64
[INFO ] - java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
[INFO ] - java.runtime.version: 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
[INFO ] - java.vm.specification.name: Java Virtual Machine Specification
[INFO ] - user.dir: /home/christoph/IdeaProjects/djl/integration
[INFO ] - sun.java.launcher: SUN_STANDARD
[INFO ] - user.country: US
[INFO ] - sun.os.patch.level: unknown
[INFO ] - java.vm.name: OpenJDK 64-Bit Server VM
[INFO ] - file.encoding.pkg: sun.io
[INFO ] - path.separator: :
[INFO ] - java.vm.vendor: Private Build
[INFO ] - java.vendor.url: http://java.oracle.com/
[INFO ] - sun.boot.library.path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
[INFO ] - java.vm.version: 25.242-b08
[INFO ] - java.runtime.name: OpenJDK Runtime Environment
[INFO ] - 
[INFO ] - ----------Environment Variables----------
[INFO ] - PATH: /usr/local/cuda/bin:/home/christoph/.local/bin:/home/christoph/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
[INFO ] - LC_MEASUREMENT: de_DE.UTF-8
[INFO ] - XAUTHORITY: /home/christoph/.Xauthority
[INFO ] - LC_TELEPHONE: de_DE.UTF-8
[INFO ] - XDG_DATA_DIRS: /usr/share/cinnamon:/usr/share/gnome:/home/christoph/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
[INFO ] - GDMSESSION: cinnamon
[INFO ] - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
[INFO ] - XDG_CURRENT_DESKTOP: X-Cinnamon
[INFO ] - SSH_AGENT_PID: 1493
[INFO ] - COLORTERM: truecolor
[INFO ] - LD_LIBRARY_PATH: /usr/local/cuda/lib64:
[INFO ] - LC_PAPER: de_DE.UTF-8
[INFO ] - SESSION_MANAGER: local/bishop:@/tmp/.ICE-unix/1428,unix/bishop:/tmp/.ICE-unix/1428
[INFO ] - LOGNAME: christoph
[INFO ] - PWD: /home/christoph/IdeaProjects/djl
[INFO ] - LANGUAGE: en_US
[INFO ] - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
[INFO ] - SHELL: /bin/bash
[INFO ] - LESSOPEN: | /usr/bin/lesspipe %s
[INFO ] - LC_ADDRESS: de_DE.UTF-8
[INFO ] - OLDPWD: /home/christoph/IdeaProjects/djl
[INFO ] - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
[INFO ] - GNOME_TERMINAL_SCREEN: /org/gnome/Terminal/screen/cdbd2b41_45b6_4c94_aa70_241e01b6353f
[INFO ] - GTK_MODULES: gail:atk-bridge
[INFO ] - XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
[INFO ] - XDG_SESSION_DESKTOP: cinnamon
[INFO ] - LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
[INFO ] - SHLVL: 1
[INFO ] - LC_IDENTIFICATION: de_DE.UTF-8
[INFO ] - LESSCLOSE: /usr/bin/lesspipe %s %s
[INFO ] - LC_MONETARY: de_DE.UTF-8
[INFO ] - TERM: xterm-256color
[INFO ] - XDG_CONFIG_DIRS: /etc/xdg/xdg-cinnamon:/etc/xdg
[INFO ] - GNOME_TERMINAL_SERVICE: :1.84
[INFO ] - LANG: en_US.UTF-8
[INFO ] - XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
[INFO ] - XDG_SESSION_ID: c2
[INFO ] - XDG_SESSION_TYPE: x11
[INFO ] - DISPLAY: :0
[INFO ] - CINNAMON_VERSION: 4.4.8
[INFO ] - LC_NAME: de_DE.UTF-8
[INFO ] - _: ./gradlew
[INFO ] - GDM_LANG: en_US
[INFO ] - XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/christoph
[INFO ] - GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
[INFO ] - DESKTOP_SESSION: cinnamon
[INFO ] - USER: christoph
[INFO ] - VTE_VERSION: 5202
[INFO ] - QT_ACCESSIBILITY: 1
[INFO ] - LC_NUMERIC: de_DE.UTF-8
[INFO ] - GJS_DEBUG_OUTPUT: stderr
[INFO ] - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
[INFO ] - XDG_SEAT: seat0
[INFO ] - GTK_OVERLAY_SCROLLING: 1
[INFO ] - QT_QPA_PLATFORMTHEME: qt5ct
[INFO ] - XDG_VTNR: 7
[INFO ] - XDG_RUNTIME_DIR: /run/user/1000
[INFO ] - HOME: /home/christoph
[INFO ] - 
[INFO ] - ----------Default Engine----------
```
(the output did not print anything about the Default Engine, it hangs for minutes after that, I had to abort)

The output of `locale` is: 
```
    LANG=en_US.UTF-8
    LANGUAGE=en_US
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC=de_DE.UTF-8
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY=de_DE.UTF-8
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER=de_DE.UTF-8
    LC_NAME=de_DE.UTF-8
    LC_ADDRESS=de_DE.UTF-8
    LC_TELEPHONE=de_DE.UTF-8
    LC_MEASUREMENT=de_DE.UTF-8
    LC_IDENTIFICATION=de_DE.UTF-8
    LC_ALL=
```

The culprit is `LC_NUMERIC`. If set to `en_US.UTF-8` the calculations yield the expected result.

**Comment by frankfliu** [comment] 2020-04-09 01:03
@chenkelmann thank you for report this issue.
Excellent job on your thorough investigation and finding of the root cause.
We will find a proper way to resolve this issue.

**Comment by stu1130** [comment] 2020-04-09 01:12
I will take a look at this

**Comment by stu1130** [comment] 2020-04-17 21:38
Hey @chenkelmann the workaround for locale issue has been merged.
Once MXNet fix is merged, we will revert the workaround
see https://github.com/apache/incubator-mxnet/pull/17177

**Closed by stu1130** 2020-04-17 21:38 UTC
Labels: bug

**Comment by chenkelmann** [comment] 2020-04-20 08:56
Cool, thank you very much!
