### ISSUE TITLE
TrainWithOptimizers throws TrainingDivergedException

### ISSUE THREAD

**Issue by salamanders** [awslabs/djl#17] opened 2020-01-13 19:53 UTC
## Description
TrainWithOptimizers throws TrainingDivergedException
Possibly caused by `Metric name not found: epoch`

### Expected Behavior
Run most things in ai.djl.examples.training.* out of the box.

### Error Message

```
mymac:examples me $ ./gradlew run -Dmain=ai.djl.examples.training.TrainWithOptimizers

> Task :run
[INFO ] - Running ExampleTrainingListener on: cpu(0).
[INFO ] - Load library 1.6.0 in 0.106 ms.
Training:      0% |█                                       | Accuracy: 0.19, SoftmaxCrossEntropyLoss: 4.72, speed: 8.18 images/sec                                                        [INFO ] - Training: 1562 batches15s]
[INFO ] - Validation: 312 batches
[INFO ] - train P50: 3914.031 ms, P90: 3914.031 ms
[INFO ] - forward P50: 20.862 ms, P90: 21.610 ms
[INFO ] - training-metrics P50: 3606.591 ms, P90: 5841.697 ms
[INFO ] - backward P50: 8.703 ms, P90: 11.023 ms
[INFO ] - step P50: 39.751 ms, P90: 39.751 ms
Exception in thread "main" ai.djl.TrainingDivergedException: The Loss became NaN, try reduce learning rate,add clipGradient option to your optimizer, check input data and loss calculation.
        at ai.djl.examples.training.util.ExampleTrainingListener.onTrainingBatch(ExampleTrainingListener.java:87)
        at ai.djl.mxnet.engine.MxTrainer.lambda$trainBatch$3(MxTrainer.java:142)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at ai.djl.mxnet.engine.MxTrainer.trainBatch(MxTrainer.java:142)
        at ai.djl.examples.training.util.TrainingUtils.fit(TrainingUtils.java:47)
        at ai.djl.examples.training.TrainWithOptimizers.runExample(TrainWithOptimizers.java:107)
        at ai.djl.examples.training.TrainWithOptimizers.main(TrainWithOptimizers.java:69)
        Suppressed: java.lang.IllegalArgumentException: Metric name not found: epoch
                at ai.djl.metric.Metrics.percentile(Metrics.java:135)
                at ai.djl.examples.training.util.ExampleTrainingListener.onTrainingEnd(ExampleTrainingListener.java:168)
                at ai.djl.mxnet.engine.MxTrainer.lambda$close$10(MxTrainer.java:344)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
                at ai.djl.mxnet.engine.MxTrainer.close(MxTrainer.java:344)
                at ai.djl.examples.training.TrainWithOptimizers.runExample(TrainWithOptimizers.java:96)
                ... 1 more

> Task :run FAILED

FAILURE: Build failed with an exception.
```

## How to Reproduce?
git clone from repository, then start running examples.

### Steps to reproduce

1. `./gradlew run -Dmain=ai.djl.examples.training.TrainWithOptimizers`
2.

## What have you tried to solve it?

1. Nothing

## Environment Info
Please provide the following information:

* Operating System: OSX
* Hardware(Machine) Info: Macbook pro
* CUDA version(if available): None
* Deep Java Library version: ?
* MXNet version: ?

**Comment by keerthanvasist** [comment] 2020-01-14 00:59
@salamanders Thank you for reporting this issue. I will look into it in the next couple of days.

**Comment by frankfliu** [comment] 2020-01-14 03:00
@salamanders,
This issue is a regression in recently change, we are working on it. For the time being, please try stable vesion: v0.2.1

**Comment by salamanders** [comment] 2020-01-15 17:30
I'd like to, but I ran into issues.  Is there a standalone example using maven?  When I tried to include the 0.2.1 libs, it complained that the version was not found.

**Comment by frankfliu** [comment] 2020-01-16 06:13
@salamanders 
TrainingDivergedException should have been resolved in latest code in master branch.

It looks like there is an issue with sonatype, we are working with sonatype to resolve 0.2.1 release artifact issue.

**Comment by frankfliu** [comment] 2020-01-16 20:01
@salamanders 
sonatype purge CDN cache. Now you should be able to use 0.2.1 artifacts.

**Closed** 2020-01-17 03:12 UTC
Labels: bug
